version: '3'
services:
  t5_sum_service: 
    container_name: t5_sum_service
    build:
      context: .
      dockerfile: Dockerfile 
    ports:
      - "6000:6000" # default ports for seldon services
      - "9000:9000"
    volumes:
      - ./model/:/app/model/ 